timeout: 0

/RockOS
    protocol: multiboot1
    kernel_path: boot():/boot/rockos.bin
    resolution: 1024x768x32
    textmode: no
    module_path: boot():/boot/rockos-install.img
    module_string: ROCKOS_INSTALL_IMAGE
